version: '3'
services:
  postgres:
    container_name: postgres-auth
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - auth
  myapp:
    container_name: auth-service
    ports:
      - "3000:3000"
    build:
      context: ./
      dockerfile: build/Dockerfile
    restart: always
    networks:
      - auth
    volumes:
      - ./config/config.yaml:/app/config.yaml:ro
    environment:
      - APP_MODE=dev
networks:
  auth:
    driver: bridge
volumes:
  postgres-vol: